### ISSUE TITLE
Requesting some info

### ISSUE THREAD

**Issue by IriaSomobu** [Chris-Baker/RogueStar#2]
Hello!
What are you doing here?
(Sorry, I have no time to compile and run it myself)

**Comment by Chris-Baker** [comment]
Hi there! This is a multiplayer platform game using LibGDX. It is very early WIP at the moment but you can run the server and desktop using:

gradle server:run
gradle desktop:run

I'll add a proper readme at some point when this is actually usable.

Cheers,
Chris

**Comment by IriaSomobu** [comment]
That's sounds interesting.
Can you add any screenshots, please?
Also, I can help you to port it on android (not now, some time later) - if you interested of course.

**Comment by Chris-Baker** [comment]
I haven't done any view stuff yet, it's just networked physics with debug draw. I'll add some screenshots when it looks a bit more interesting.

Re Android port, thanks for the offer, it should more or less work already because of LibGDX. I'm not sure how well the controls will map to a touch screen, but feel free to have a play with it at some point.

**Comment by IriaSomobu** [comment]
Okey.
